### ISSUE TITLE
Imported realm from 'realm-test.json' doesn't prompt for trusted-device and OTP-device during login - (RESOLVED)

### ISSUE THREAD

**Issue by jtang206** [wouterh-dev/keycloak-spi-trusted-device#4]
Imported the sample JSON 'realm-test.json' file for the realm **test**.
Authentication assigned for "Browser flow": '**2FA - Browser**'
* Keycloak version: **22.0.3** as defined in current 'Dockerfile'
* Postgres version: **14** as defined in current 'docker-compose.yml'
* Login only prompts for "Username & Password"
* **Not** seeing any request to add "OTP device"
* **Not** seeing any request to trust device (current browser used for login)

This instance is running with "start-dev" using the vanilla setup directly from 'Github' using the 'run-dev.sh' script.

"Browser" auth-flow for the 'test' realm from the 'imported JSON' file:
![Keycloak-Administration-UI-2FA_Browser AuthFlow](https://github.com/wouterh-dev/keycloak-spi-trusted-device/assets/36016695/44a76ece-181a-4344-b129-f22763b4f301)

**Comment by jtang206** [comment]
Hi,
Has there been any updates on this finding? Am I configuring the browser-flow incorrectly or something?
If you're able to provide a good example of a realm-export JSON that works, could you include it in the response?
Thanks for all your help on this.
-Justin

**Comment by zawadaa** [comment]
Hi, I'm at the same point. :-(
KC22 from docker, build with providers, realm imported.
In my realm, I can't add `Authenticator types`
![image](https://github.com/wouterh-dev/keycloak-spi-trusted-device/assets/5627246/05b1f623-8242-4e52-8333-58bbc7374e7c)
 in "Condition - Credential Configured config"
No errors in logs. Any ideas?

**Comment by zawadaa** [comment]
Imported realm doesn't work because of "client scope permissions":
After https://keycloak.discourse.group/t/what-could-cause-the-users-account-page-to-be-forbidden/16285
works.
In existing realms I still can't add "Authenticator types" in the Condition.

**Comment by jtang206** [comment]
Thanks for the info @zawadaa ...
That cleared my user so it has the correct access to add an TOTP-device to its credential-list.
Once an OTP-device is configured, then the 'trusted-device' prompt appears.
I'll resolve and close this issue as the condition describes that:
* If **OTP-device is configured**, then "Prompt 2FA". 
* Once TOTP entered successfully, then display the "Trust this device?" dialog.

**Comment by wouterh-dev** [comment]
Newer versions of Keycloak do not seem compatible with exports generated by older versions. The above comments list a workaround.

It should work if you configure the authentication flow manually (see readme).

**Comment by wouterh-dev** [comment]
Not being able to configure Authenticator types is a Keycloak bug, see https://github.com/wouterh-dev/keycloak-spi-trusted-device/issues/6#issuecomment-2149887435
